import {
  DragHandleIcon,
  DnsSettingsIcon,
  ClockIcon,
} from "@shopify/polaris-icons";

export const cardEntries = [
  {
    title: "Installed Apps",
    number: 10,
    supkeyword: "",
    icon: DragHandleIcon,
  },
  {
    title: "Transfer size",
    number: 458,
    supkeyword: "kib",
    icon: DnsSettingsIcon,
  },
  {
    title: "Main-Thread Blocking Time",
    number: 10,
    supkeyword: "ms",
    icon: ClockIcon,
  },
  {
    title: "Total Load time for all apps",
    number: 2.8,
    supkeyword: "s",
    icon: ClockIcon,
  },
];

import {
  AlertDiamondIcon,
  AlertTriangleIcon,  
} from '@shopify/polaris-icons';


export const TableData = [
  {
    name: `Stamped.io`,
    size: 43,
    lastUsage: 14,
    avgLoadTime: 1,
    icon: <AlertDiamondIcon />,
    image: AlertDiamondIcon,
    details: [
      [
        "http://www.faxquote.com//Stamped.io",
        "43 KIB",
        "4,229 ms",
        "240 ms",
        "13 ms",
        "",
      ],
      [
        "http://www.faxquote.com//Stamped.io",
        "43 KIB",
        "4,229 ms",
        "240 ms",
        "13 ms",
        "",
      ],
      [
        "http://www.faxquote.com//Stamped.io",
        "43 KIB",
        "4,229 ms",
        "240 ms",
        "13 ms",
        "",
      ],
      [
        "http://www.faxquote.com//Stamped.io",
        "43 KIB",
        "4,229 ms",
        "240 ms",
        "13 ms",
        "",
      ],
    ],
  },
  {
    name: "Polyfill service",
    size: 38,
    lastUsage: 11,
    avgLoadTime: 1,
    icon: <  AlertTriangleIcon />,
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//PolyfillService",
        "20 KIB",
        "1,229 ms",
        "100 ms",
        "5 ms",
        "",
      ],
      [
        "http://www.faxquote.com//PolyfillService",
        "21 KIB",
        "1,230 ms",
        "110 ms",
        "6 ms",
        "",
      ],
      [
        "http://www.faxquote.com//PolyfillService",
        "22 KIB",
        "1,231 ms",
        "120 ms",
        "7 ms",
        "",
      ],
      [
        "http://www.faxquote.com//PolyfillService",
        "23 KIB",
        "1,232 ms",
        "130 ms",
        "8 ms",
        "",
      ],
    ],
  },
  {
    name: "Google Fonts",
    size: 25,
    lastUsage: 8,
    avgLoadTime: 1,
    icon: <  AlertTriangleIcon />,
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//GoogleFonts",
        "30 KIB",
        "2,229 ms",
        "150 ms",
        "10 ms",
        "",
      ],
      [
        "http://www.faxquote.com//GoogleFonts",
        "31 KIB",
        "2,230 ms",
        "155 ms",
        "11 ms",
        "",
      ],
    ],
  },
  {
    name: "Google CDN",
    size: 15,
    lastUsage: 1,
    avgLoadTime: 1,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//GoogleCDN",
        "28 KIB",
        "2,000 ms",
        "120 ms",
        "8 ms",
        "",
      ],
      [
        "http://www.faxquote.com//GoogleCDN",
        "29 KIB",
        "2,010 ms",
        "125 ms",
        "9 ms",
        "",
      ],
    ],
  },
  {
    name: "Suite For Google Shopping Feed",
    size: 15,
    lastUsage: 2,
    avgLoadTime: 1,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//GoogleShoppingFeed",
        "25 KIB",
        "1,800 ms",
        "110 ms",
        "7 ms",
        "",
      ],
      [
        "http://www.faxquote.com//GoogleShoppingFeed",
        "26 KIB",
        "1,810 ms",
        "115 ms",
        "8 ms",
        "",
      ],
    ],
  },
  {
    name: "Ali Reviews - Product Reviews",
    size: 1,
    lastUsage: 5,
    avgLoadTime: 1.2,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//AliReviews",
        "27 KIB",
        "1,900 ms",
        "130 ms",
        "9 ms",
        "",
      ],
      [
        "http://www.faxquote.com//AliReviews",
        "28 KIB",
        "1,910 ms",
        "135 ms",
        "10 ms",
        "",
      ],
    ],
  },
  {
    name: "Pinterest",
    size: 31,
    lastUsage: 11,
    avgLoadTime: 2,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//Pinterest",
        "26 KIB",
        "1,850 ms",
        "125 ms",
        "8 ms",
        "",
      ],
      [
        "http://www.faxquote.com//Pinterest",
        "27 KIB",
        "1,860 ms",
        "130 ms",
        "9 ms",
        "",
      ],
    ],
  },
  {
    name: "Facebook channel",
    size: 45,
    lastUsage: 6,
    avgLoadTime: 2,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//FacebookChannel",
        "29 KIB",
        "2,100 ms",
        "140 ms",
        "10 ms",
        "",
      ],
      [
        "http://www.faxquote.com//FacebookChannel",
        "30 KIB",
        "2,110 ms",
        "145 ms",
        "11 ms",
        "",
      ],
    ],
  },
  {
    name: "Third Party Scripts",
    size: 52,
    lastUsage: 8,
    avgLoadTime: 1.3,
    icon: "",
    image:   AlertTriangleIcon,
    details: [
      [
        "http://www.faxquote.com//ThirdPartyScripts",
        "32 KIB",
        "2,200 ms",
        "150 ms",
        "12 ms",
        "",
      ],
      [
        "http://www.faxquote.com//ThirdPartyScripts",
        "33 KIB",
        "2,210 ms",
        "155 ms",
        "13 ms",
        "",
      ],
    ],
  },
];
